# Install UV 
FROM python:3.11-bullseye
COPY --from=ghcr.io/astral-sh/uv:0.6.3 /uv /bin/uv

ENV PYTHONUNBUFFERED True
ENV ENVIRONMENT production

WORKDIR /opt

# Copy the lockfile and `pyproject.toml` into the image
COPY uv.lock /opt/uv.lock
COPY pyproject.toml /opt/pyproject.toml

# Install dependencies
RUN uv sync --frozen --no-install-project

COPY ./src /opt/
COPY LICENSE /opt/LICENSE
COPY README.md /opt/README.md

# Sync the project
RUN uv sync --frozen
ENV PATH="/opt/.venv/bin:$PATH"

EXPOSE 8001

# These args is tailored to the docker-compose setup.
CMD ["uv", "run", "weather-agent", "--ollama-host", "http://172.28.1.5:11434", "--ollama-model", "granite3.2:8b", "--host", "0.0.0.0"]