# Install UV
FROM python:3.11-bullseye
COPY --from=ghcr.io/astral-sh/uv:0.6.3 /uv /bin/uv

ENV PYTHONUNBUFFERED True
ENV ENVIRONMENT production

WORKDIR /opt

# Copy the lockfile and `pyproject.toml` into the image
COPY uv.lock /opt/uv.lock
COPY pyproject.toml /opt/pyproject.toml

# Install dependencies
RUN uv sync --frozen --no-install-project

COPY ./src /opt/
COPY LICENSE /opt/LICENSE
COPY README.md /opt/README.md

# Sync the project
RUN uv sync --frozen
ENV PATH="/opt/.venv/bin:$PATH"

# We change the a2a client time out in the package. As of writing this is not an argument to the client - therefore this here hack
RUN sed "s/timeout=30/timeout=120/" /opt/.venv/lib/python3.13/site-packages/google_a2a/common/client/client.py > client.py && \
    rm -v /opt/.venv/lib/python3.13/site-packages/google_a2a/common/client/client.py && \
    mv -v client.py /opt/.venv/lib/python3.13/site-packages/google_a2a/common/client/client.py

EXPOSE 8090

# These args is tailored to the docker-compose setup.
CMD ["uv", "run", "weather_agent/a2a_agent_mcp_tool.py"]